
export enum ViewState {
    DASHBOARD = 'DASHBOARD',
    LEARNING_HISTORY = 'LEARNING_HISTORY',
    MODULE_EXPLORATION = 'MODULE_EXPLORATION',
    CURRICULUM_DESIGN = 'CURRICULUM_DESIGN',
    AI_RECOMMENDATION = 'AI_RECOMMENDATION',
    MODULE_STATISTICS = 'MODULE_STATISTICS',
    MODULE_CART = 'MODULE_CART'
}

export interface Subject {
    id: string;
    name: string;
    credit: number;
    type: 'major' | 'general' | 'extra';
    dept?: string;
}

export interface Track {
    id: number;
    title: string;
    subjects: Subject[];
    description?: string;
    isAutoGenerated?: boolean;
}

export interface RecommendationItem {
    title: string;
    dept: string; // Department or composition (e.g., "Business + CS")
    reason: string;
    matchType: 'Strong' | 'Normal'; // Strong = 강력 추천
    tags?: string[];
}

export interface AcademicRecommendations {
    microDegrees: RecommendationItem[];
    doubleMajors: RecommendationItem[]; // 36 credits
    minors: RecommendationItem[];       // 24 credits
}

export interface UserProfile {
    major: string;
    interests: string;
    aptitude: string;
}
